// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/632a54bc21b8e1980e08af73
###
GET http://localhost:8080/contacts/632a59d096db18cff1732429
###
GET http://localhost:8080/contacts/632a59d096db18cff173242a
###
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
  "firstName": "Susanna",
  "lastName": "Burns",
  "email": "susanna@gmail.com",
  "favoriteColor": "pink",
  "birthday": "2018-08-01T07:00:00.000Z"
}
###
DELETE http://localhost:8080/contacts/6338606939faf708874b0cc7
###
PUT http://localhost:8080/contacts/63384c2ef7c3760821146ac0
content-type: application/json

{
  "favoriteColor": "brown"
}

// PRODUCTION Deploy
###
GET https://cse341-w01-pa.onrender.com/contacts
###
GET https://cse341-w01-pa.onrender.com/contacts/632a54bc21b8e1980e08af73
###
GET https://cse341-w01-pa.onrender.com/contacts/632a59d096db18cff1732429
###
GET https://cse341-w01-pa.onrender.com/contacts/632a59d096db18cff173242a
###
POST http://cse341-w01-pa.onrender.com/contacts HTTP/1.1
content-type: application/json

{
  "firstName": "Susanna",
  "lastName": "Burns",
  "email": "susanna@gmail.com",
  "favoriteColor": "pink",
  "birthday": "2018-08-01T07:00:00.000Z"
}
###
DELETE http://cse341-w01-pa.onrender.com/contacts/63384e378497a42e04114337
###
PUT http://cse341-w01-pa.onrender.com/contacts/63384c2ef7c3760821146ac0
content-type: application/json

{
  "favoriteColor": "Blue"
}